FROM golang:1.18.3-buster

ARG USER_NAME=$USER_NAME
ARG USER_ID=$USER_ID
ARG GROUP_NAME=$GROUP_NAME
ARG GROUP_ID=$GROUP_ID
ARG TZ=$TZ
ENV TZ=$TZ

RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y sudo

RUN apt install -y jq tree diffutils nano vim

RUN groupadd -g $GROUP_ID $GROUP_NAME && \
    useradd -s /bin/bash -u $USER_ID -g $GROUP_ID -G sudo $USER_NAME -r -d /home/$USER_NAME -M && \
    echo "$USER_NAME   ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER $USER_NAME
WORKDIR /home/$USER_NAME
